import { enemyArchetypeId } from "../ContentIds.ts";
import type { EnemyArchetypeDef } from "../ContentTypes.ts";

export const prototypeEnemyArchetypes: readonly EnemyArchetypeDef[] = [
  {
    id: enemyArchetypeId("enemy.bat"),
    displayName: "Bat",
    spriteKey: "enemy_bat",
    behavior: "chase",
    maxHp: 10,
    moveSpeed: 62,
    radius: 10,
    contactDamage: 8,
    xpValue: 1,
    collisionFlags: 1,
  },
  {
    id: enemyArchetypeId("enemy.skeleton"),
    displayName: "Skeleton",
    spriteKey: "enemy_skeleton",
    behavior: "chase",
    maxHp: 24,
    moveSpeed: 42,
    radius: 14,
    contactDamage: 12,
    xpValue: 2,
    collisionFlags: 1,
  },
  {
    id: enemyArchetypeId("enemy.ghost"),
    displayName: "Ghost",
    spriteKey: "enemy_ghost",
    behavior: "chase",
    maxHp: 18,
    moveSpeed: 52,
    radius: 13,
    contactDamage: 10,
    xpValue: 3,
    collisionFlags: 1,
  },
  {
    id: enemyArchetypeId("enemy.miniboss_executioner"),
    displayName: "Executioner",
    spriteKey: "enemy_miniboss_executioner",
    behavior: "chase",
    maxHp: 220,
    moveSpeed: 34,
    radius: 24,
    contactDamage: 22,
    xpValue: 12,
    collisionFlags: 1,
  },
  {
    id: enemyArchetypeId("enemy.boss_lich"),
    displayName: "Lich King",
    spriteKey: "enemy_boss_lich",
    behavior: "chase",
    maxHp: 520,
    moveSpeed: 28,
    radius: 30,
    contactDamage: 30,
    xpValue: 24,
    collisionFlags: 1,
  },
];
