import { projectileId, weaponId } from "../ContentIds";
import type { WeaponDef } from "../ContentTypes";

export const prototypeWeapons: readonly WeaponDef[] = [
  {
    id: weaponId("weapon.magic_bolt"),
    displayName: "Magic Bolt",
    description: "Auto-fires a fast projectile at the nearest enemy.",
    iconKey: "weapon_magic_bolt",
    behavior: "projectile",
    maxLevel: 8,
    baseCooldownSeconds: 0.9,
    shotsPerFire: 1,
    targeting: "nearest_enemy",
    projectileId: projectileId("projectile.magic_bolt"),
    baseDamageMultiplier: 1,
    baseAreaRadius: 0,
    baseDurationSeconds: 0,
    basePierceBonus: 0,
  },
  {
    id: weaponId("weapon.holy_aura"),
    displayName: "Holy Aura",
    description: "Damages enemies within a short radius around the player.",
    iconKey: "weapon_holy_aura",
    behavior: "aura",
    maxLevel: 8,
    baseCooldownSeconds: 1.2,
    shotsPerFire: 1,
    targeting: "self",
    projectileId: null,
    baseDamageMultiplier: 0.7,
    baseAreaRadius: 42,
    baseDurationSeconds: 0.15,
    basePierceBonus: 99,
  },
  {
    id: weaponId("weapon.arc_nova"),
    displayName: "Arc Nova",
    description: "Releases a radial burst around the player.",
    iconKey: "weapon_arc_nova",
    behavior: "nova",
    maxLevel: 8,
    baseCooldownSeconds: 2.4,
    shotsPerFire: 8,
    targeting: "self",
    projectileId: null,
    baseDamageMultiplier: 1.2,
    baseAreaRadius: 56,
    baseDurationSeconds: 0.05,
    basePierceBonus: 99,
  },
];
